name = "ai-assistant-library"
compatibility_date = "2023-01-01"

[site]
bucket = "./"
include = ["images/**", "*.html", "*.css", "*.js", "*.webp", "*.json", "generated-configs/**", "gallery/**"]

[build.upload]
format = "service-worker"